env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-native
  - '@typescript-eslint'
  - prettier
rules:
  prefer-const: error
  react/display-name: off
  react/prop-types: off
  prettier/prettier: error
  react/react-in-jsx-scope: off
  "@typescript-eslint/no-unused-vars": off
